version: "3.7"

services:
  #Wordpress
  wp:
    image: wordpress:5.2.2
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    restart: always
    volumes:
       - wp_data:/var/wwww/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"
    depends_on:
      - db

  #wpcli
  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  #Database
  db:
    image: mysql:8.0.17
    volumes:
       - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: root
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  #Phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 0.0.0.0:8080:80
      - 0.0.0.0:443:443
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  
volumes:
    wp_data:
    db_data:
